# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarWasherViewer' do
  use_frameworks!

  pod 'Charts'
  pod "MonthYearPicker", '~> 4.0.2'
  pod 'SwiftKeychainWrapper'
end
